### ISSUE TITLE
[ENHANCEMENT]allow to add finger print authentification and disable finger print if user don't want.

### ISSUE THREAD

**Issue by ptcmyanmar** [stoodkev/hive-keychain-mobile#22]
**Is your feature request related to a problem? Please describe.**
App is aasking to authentificate even if  user don't add finger print to unlock app. And also there is no place to add finger print if your want to. 

**Describe the solution you'd like**
As I mention add an option to add finger print and allow to disable finger print from app level if your don't want to use finger print. Allow user to choose pin code or finger print to unlock the app.

**Describe alternatives you've considered**
No alternative currently. 

**Additional context**
No need I think.

**Comment by stoodkev** [comment]
Already answered countless time on both Discord and Hive.
